/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BatchedDistribusiResult {
  'gagal' : Array<{ 'error' : string, 'sasaranId' : bigint }>,
  'sukses' : Array<DistribusiRecord>,
}
export interface DistribusiRecord {
  'id' : bigint,
  'idPaket' : bigint,
  'idSasaran' : bigint,
  'keterangan' : [] | [string],
  'statusDistribusi' : DistribusiStatus,
  'jumlahPaket' : bigint,
  'tanggalDistribusi' : Time,
}
export type DistribusiStatus = { 'pending' : null } |
  { 'terdistribusi' : null } |
  { 'dalamProses' : null } |
  { 'tidakTerkirim' : null };
export type Jenis = { 'susuTambahan' : null } |
  { 'lainnya' : string } |
  { 'makananSiapSaji' : null } |
  { 'multivitamin' : null } |
  { 'paketSembako' : null };
export type Kategori = { 'balita' : null } |
  { 'tidakDitentukan' : null } |
  { 'ibuMenyusui' : null } |
  { 'ibuHamil' : null };
export interface PaketMBGRecord {
  'id' : bigint,
  'nama' : string,
  'jenis' : Jenis,
  'keterangan' : [] | [string],
}
export interface PendingBatchedDistribusi {
  'idPaket' : bigint,
  'sasaranIds' : Array<bigint>,
  'keterangan' : [] | [string],
  'statusDistribusi' : DistribusiStatus,
  'jumlahPaket' : bigint,
  'tanggalDistribusi' : Time,
}
export interface SasaranRecord {
  'id' : bigint,
  'status' : Status,
  'alamat' : string,
  'nama' : string,
  'nomorIdentitas' : string,
  'kategori' : Kategori,
  'catatan' : [] | [string],
}
export type Status = { 'aktif' : null } |
  { 'nonAktif' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cariSasaranByNama' : ActorMethod<[string], Array<SasaranRecord>>,
  'catatDistribusiBatched' : ActorMethod<
    [PendingBatchedDistribusi],
    BatchedDistribusiResult
  >,
  'editDistribusi' : ActorMethod<
    [bigint, bigint, bigint, Time, DistribusiStatus, [] | [string]],
    DistribusiRecord
  >,
  'filterDistribusiByTanggal' : ActorMethod<
    [Time, Time],
    Array<DistribusiRecord>
  >,
  'filterSasaranByKategori' : ActorMethod<[Kategori], Array<SasaranRecord>>,
  'filterSasaranByStatus' : ActorMethod<[boolean], Array<SasaranRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDataUntukLaporan' : ActorMethod<
    [Time, Time],
    {
      'distribusi' : Array<DistribusiRecord>,
      'paket' : Array<PaketMBGRecord>,
      'sasaran' : Array<SasaranRecord>,
    }
  >,
  'getDistribusi' : ActorMethod<[bigint], [] | [DistribusiRecord]>,
  'getDistribusiByPaket' : ActorMethod<[bigint], Array<DistribusiRecord>>,
  'getDistribusiBySasaran' : ActorMethod<[bigint], Array<DistribusiRecord>>,
  'getDistribusiByStatus' : ActorMethod<
    [DistribusiStatus],
    Array<DistribusiRecord>
  >,
  'getLaporanByKategori' : ActorMethod<
    [Kategori, Time, Time],
    {
      'distribusi' : Array<DistribusiRecord>,
      'paket' : Array<PaketMBGRecord>,
      'sasaran' : Array<SasaranRecord>,
    }
  >,
  'getPaket' : ActorMethod<[bigint], [] | [PaketMBGRecord]>,
  'getSasaran' : ActorMethod<[bigint], [] | [SasaranRecord]>,
  'getSemuaDistribusi' : ActorMethod<[], Array<DistribusiRecord>>,
  'getSemuaDistribusiSortedById' : ActorMethod<[], Array<DistribusiRecord>>,
  'getSemuaDistribusiSortedByTanggal' : ActorMethod<
    [],
    Array<DistribusiRecord>
  >,
  'getSemuaPaket' : ActorMethod<[], Array<PaketMBGRecord>>,
  'getSemuaPaketSortedById' : ActorMethod<[], Array<PaketMBGRecord>>,
  'getSemuaPaketSortedByNama' : ActorMethod<[], Array<PaketMBGRecord>>,
  'getSemuaSasaran' : ActorMethod<[], Array<SasaranRecord>>,
  'getSemuaSasaranSortedById' : ActorMethod<[], Array<SasaranRecord>>,
  'getSemuaSasaranSortedByNama' : ActorMethod<[], Array<SasaranRecord>>,
  'getStatistikDistribusi' : ActorMethod<
    [],
    {
      'totalDistribusi' : bigint,
      'totalSasaran' : bigint,
      'totalPaket' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'tambahPaket' : ActorMethod<[Jenis, string, [] | [string]], PaketMBGRecord>,
  'tambahSasaran' : ActorMethod<
    [string, string, string, [] | [string], [] | [Kategori]],
    SasaranRecord
  >,
  'ubahStatusSasaran' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];