/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'aktif' : IDL.Null,
  'nonAktif' : IDL.Null,
});
export const Kategori = IDL.Variant({
  'balita' : IDL.Null,
  'tidakDitentukan' : IDL.Null,
  'ibuMenyusui' : IDL.Null,
  'ibuHamil' : IDL.Null,
});
export const SasaranRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'alamat' : IDL.Text,
  'nama' : IDL.Text,
  'nomorIdentitas' : IDL.Text,
  'kategori' : Kategori,
  'catatan' : IDL.Opt(IDL.Text),
});
export const DistribusiStatus = IDL.Variant({
  'pending' : IDL.Null,
  'terdistribusi' : IDL.Null,
  'dalamProses' : IDL.Null,
  'tidakTerkirim' : IDL.Null,
});
export const Time = IDL.Int;
export const PendingBatchedDistribusi = IDL.Record({
  'idPaket' : IDL.Nat,
  'sasaranIds' : IDL.Vec(IDL.Nat),
  'keterangan' : IDL.Opt(IDL.Text),
  'statusDistribusi' : DistribusiStatus,
  'jumlahPaket' : IDL.Nat,
  'tanggalDistribusi' : Time,
});
export const DistribusiRecord = IDL.Record({
  'id' : IDL.Nat,
  'idPaket' : IDL.Nat,
  'idSasaran' : IDL.Nat,
  'keterangan' : IDL.Opt(IDL.Text),
  'statusDistribusi' : DistribusiStatus,
  'jumlahPaket' : IDL.Nat,
  'tanggalDistribusi' : Time,
});
export const BatchedDistribusiResult = IDL.Record({
  'gagal' : IDL.Vec(IDL.Record({ 'error' : IDL.Text, 'sasaranId' : IDL.Nat })),
  'sukses' : IDL.Vec(DistribusiRecord),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Jenis = IDL.Variant({
  'susuTambahan' : IDL.Null,
  'lainnya' : IDL.Text,
  'makananSiapSaji' : IDL.Null,
  'multivitamin' : IDL.Null,
  'paketSembako' : IDL.Null,
});
export const PaketMBGRecord = IDL.Record({
  'id' : IDL.Nat,
  'nama' : IDL.Text,
  'jenis' : Jenis,
  'keterangan' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cariSasaranByNama' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SasaranRecord)],
      ['query'],
    ),
  'catatDistribusiBatched' : IDL.Func(
      [PendingBatchedDistribusi],
      [BatchedDistribusiResult],
      [],
    ),
  'editDistribusi' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, Time, DistribusiStatus, IDL.Opt(IDL.Text)],
      [DistribusiRecord],
      [],
    ),
  'filterDistribusiByTanggal' : IDL.Func(
      [Time, Time],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'filterSasaranByKategori' : IDL.Func(
      [Kategori],
      [IDL.Vec(SasaranRecord)],
      ['query'],
    ),
  'filterSasaranByStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(SasaranRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDataUntukLaporan' : IDL.Func(
      [Time, Time],
      [
        IDL.Record({
          'distribusi' : IDL.Vec(DistribusiRecord),
          'paket' : IDL.Vec(PaketMBGRecord),
          'sasaran' : IDL.Vec(SasaranRecord),
        }),
      ],
      ['query'],
    ),
  'getDistribusi' : IDL.Func([IDL.Nat], [IDL.Opt(DistribusiRecord)], ['query']),
  'getDistribusiByPaket' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'getDistribusiBySasaran' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'getDistribusiByStatus' : IDL.Func(
      [DistribusiStatus],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'getLaporanByKategori' : IDL.Func(
      [Kategori, Time, Time],
      [
        IDL.Record({
          'distribusi' : IDL.Vec(DistribusiRecord),
          'paket' : IDL.Vec(PaketMBGRecord),
          'sasaran' : IDL.Vec(SasaranRecord),
        }),
      ],
      ['query'],
    ),
  'getPaket' : IDL.Func([IDL.Nat], [IDL.Opt(PaketMBGRecord)], ['query']),
  'getSasaran' : IDL.Func([IDL.Nat], [IDL.Opt(SasaranRecord)], ['query']),
  'getSemuaDistribusi' : IDL.Func([], [IDL.Vec(DistribusiRecord)], ['query']),
  'getSemuaDistribusiSortedById' : IDL.Func(
      [],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'getSemuaDistribusiSortedByTanggal' : IDL.Func(
      [],
      [IDL.Vec(DistribusiRecord)],
      ['query'],
    ),
  'getSemuaPaket' : IDL.Func([], [IDL.Vec(PaketMBGRecord)], ['query']),
  'getSemuaPaketSortedById' : IDL.Func(
      [],
      [IDL.Vec(PaketMBGRecord)],
      ['query'],
    ),
  'getSemuaPaketSortedByNama' : IDL.Func(
      [],
      [IDL.Vec(PaketMBGRecord)],
      ['query'],
    ),
  'getSemuaSasaran' : IDL.Func([], [IDL.Vec(SasaranRecord)], ['query']),
  'getSemuaSasaranSortedById' : IDL.Func(
      [],
      [IDL.Vec(SasaranRecord)],
      ['query'],
    ),
  'getSemuaSasaranSortedByNama' : IDL.Func(
      [],
      [IDL.Vec(SasaranRecord)],
      ['query'],
    ),
  'getStatistikDistribusi' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalDistribusi' : IDL.Nat,
          'totalSasaran' : IDL.Nat,
          'totalPaket' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'tambahPaket' : IDL.Func(
      [Jenis, IDL.Text, IDL.Opt(IDL.Text)],
      [PaketMBGRecord],
      [],
    ),
  'tambahSasaran' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Kategori)],
      [SasaranRecord],
      [],
    ),
  'ubahStatusSasaran' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({ 'aktif' : IDL.Null, 'nonAktif' : IDL.Null });
  const Kategori = IDL.Variant({
    'balita' : IDL.Null,
    'tidakDitentukan' : IDL.Null,
    'ibuMenyusui' : IDL.Null,
    'ibuHamil' : IDL.Null,
  });
  const SasaranRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'alamat' : IDL.Text,
    'nama' : IDL.Text,
    'nomorIdentitas' : IDL.Text,
    'kategori' : Kategori,
    'catatan' : IDL.Opt(IDL.Text),
  });
  const DistribusiStatus = IDL.Variant({
    'pending' : IDL.Null,
    'terdistribusi' : IDL.Null,
    'dalamProses' : IDL.Null,
    'tidakTerkirim' : IDL.Null,
  });
  const Time = IDL.Int;
  const PendingBatchedDistribusi = IDL.Record({
    'idPaket' : IDL.Nat,
    'sasaranIds' : IDL.Vec(IDL.Nat),
    'keterangan' : IDL.Opt(IDL.Text),
    'statusDistribusi' : DistribusiStatus,
    'jumlahPaket' : IDL.Nat,
    'tanggalDistribusi' : Time,
  });
  const DistribusiRecord = IDL.Record({
    'id' : IDL.Nat,
    'idPaket' : IDL.Nat,
    'idSasaran' : IDL.Nat,
    'keterangan' : IDL.Opt(IDL.Text),
    'statusDistribusi' : DistribusiStatus,
    'jumlahPaket' : IDL.Nat,
    'tanggalDistribusi' : Time,
  });
  const BatchedDistribusiResult = IDL.Record({
    'gagal' : IDL.Vec(
      IDL.Record({ 'error' : IDL.Text, 'sasaranId' : IDL.Nat })
    ),
    'sukses' : IDL.Vec(DistribusiRecord),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Jenis = IDL.Variant({
    'susuTambahan' : IDL.Null,
    'lainnya' : IDL.Text,
    'makananSiapSaji' : IDL.Null,
    'multivitamin' : IDL.Null,
    'paketSembako' : IDL.Null,
  });
  const PaketMBGRecord = IDL.Record({
    'id' : IDL.Nat,
    'nama' : IDL.Text,
    'jenis' : Jenis,
    'keterangan' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cariSasaranByNama' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SasaranRecord)],
        ['query'],
      ),
    'catatDistribusiBatched' : IDL.Func(
        [PendingBatchedDistribusi],
        [BatchedDistribusiResult],
        [],
      ),
    'editDistribusi' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Time, DistribusiStatus, IDL.Opt(IDL.Text)],
        [DistribusiRecord],
        [],
      ),
    'filterDistribusiByTanggal' : IDL.Func(
        [Time, Time],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'filterSasaranByKategori' : IDL.Func(
        [Kategori],
        [IDL.Vec(SasaranRecord)],
        ['query'],
      ),
    'filterSasaranByStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(SasaranRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDataUntukLaporan' : IDL.Func(
        [Time, Time],
        [
          IDL.Record({
            'distribusi' : IDL.Vec(DistribusiRecord),
            'paket' : IDL.Vec(PaketMBGRecord),
            'sasaran' : IDL.Vec(SasaranRecord),
          }),
        ],
        ['query'],
      ),
    'getDistribusi' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DistribusiRecord)],
        ['query'],
      ),
    'getDistribusiByPaket' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'getDistribusiBySasaran' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'getDistribusiByStatus' : IDL.Func(
        [DistribusiStatus],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'getLaporanByKategori' : IDL.Func(
        [Kategori, Time, Time],
        [
          IDL.Record({
            'distribusi' : IDL.Vec(DistribusiRecord),
            'paket' : IDL.Vec(PaketMBGRecord),
            'sasaran' : IDL.Vec(SasaranRecord),
          }),
        ],
        ['query'],
      ),
    'getPaket' : IDL.Func([IDL.Nat], [IDL.Opt(PaketMBGRecord)], ['query']),
    'getSasaran' : IDL.Func([IDL.Nat], [IDL.Opt(SasaranRecord)], ['query']),
    'getSemuaDistribusi' : IDL.Func([], [IDL.Vec(DistribusiRecord)], ['query']),
    'getSemuaDistribusiSortedById' : IDL.Func(
        [],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'getSemuaDistribusiSortedByTanggal' : IDL.Func(
        [],
        [IDL.Vec(DistribusiRecord)],
        ['query'],
      ),
    'getSemuaPaket' : IDL.Func([], [IDL.Vec(PaketMBGRecord)], ['query']),
    'getSemuaPaketSortedById' : IDL.Func(
        [],
        [IDL.Vec(PaketMBGRecord)],
        ['query'],
      ),
    'getSemuaPaketSortedByNama' : IDL.Func(
        [],
        [IDL.Vec(PaketMBGRecord)],
        ['query'],
      ),
    'getSemuaSasaran' : IDL.Func([], [IDL.Vec(SasaranRecord)], ['query']),
    'getSemuaSasaranSortedById' : IDL.Func(
        [],
        [IDL.Vec(SasaranRecord)],
        ['query'],
      ),
    'getSemuaSasaranSortedByNama' : IDL.Func(
        [],
        [IDL.Vec(SasaranRecord)],
        ['query'],
      ),
    'getStatistikDistribusi' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalDistribusi' : IDL.Nat,
            'totalSasaran' : IDL.Nat,
            'totalPaket' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'tambahPaket' : IDL.Func(
        [Jenis, IDL.Text, IDL.Opt(IDL.Text)],
        [PaketMBGRecord],
        [],
      ),
    'tambahSasaran' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Kategori)],
        [SasaranRecord],
        [],
      ),
    'ubahStatusSasaran' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };