/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaketMBGRecord {
    id: bigint;
    nama: string;
    jenis: Jenis;
    keterangan?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PendingBatchedDistribusi {
    idPaket: bigint;
    sasaranIds: Array<bigint>;
    keterangan?: string;
    statusDistribusi: DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: Time;
}
export interface BatchedDistribusiResult {
    gagal: Array<{
        error: string;
        sasaranId: bigint;
    }>;
    sukses: Array<DistribusiRecord>;
}
export interface DistribusiRecord {
    id: bigint;
    idPaket: bigint;
    idSasaran: bigint;
    keterangan?: string;
    statusDistribusi: DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: Time;
}
export type Jenis = {
    __kind__: "susuTambahan";
    susuTambahan: null;
} | {
    __kind__: "lainnya";
    lainnya: string;
} | {
    __kind__: "makananSiapSaji";
    makananSiapSaji: null;
} | {
    __kind__: "multivitamin";
    multivitamin: null;
} | {
    __kind__: "paketSembako";
    paketSembako: null;
};
export interface SasaranRecord {
    id: bigint;
    status: Status;
    alamat: string;
    nama: string;
    nomorIdentitas: string;
    kategori: Kategori;
    catatan?: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email?: string;
}
export enum DistribusiStatus {
    pending = "pending",
    terdistribusi = "terdistribusi",
    dalamProses = "dalamProses",
    tidakTerkirim = "tidakTerkirim"
}
export enum Kategori {
    balita = "balita",
    tidakDitentukan = "tidakDitentukan",
    ibuMenyusui = "ibuMenyusui",
    ibuHamil = "ibuHamil"
}
export enum Status {
    aktif = "aktif",
    nonAktif = "nonAktif"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cariSasaranByNama(nama: string): Promise<Array<SasaranRecord>>;
    catatDistribusiBatched(pending: PendingBatchedDistribusi): Promise<BatchedDistribusiResult>;
    filterDistribusiByTanggal(start: Time, end: Time): Promise<Array<DistribusiRecord>>;
    filterSasaranByKategori(kategori: Kategori): Promise<Array<SasaranRecord>>;
    filterSasaranByStatus(aktif: boolean): Promise<Array<SasaranRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDataUntukLaporan(start: Time, end: Time): Promise<{
        distribusi: Array<DistribusiRecord>;
        paket: Array<PaketMBGRecord>;
        sasaran: Array<SasaranRecord>;
    }>;
    getDistribusi(_id: bigint): Promise<DistribusiRecord | null>;
    getDistribusiByPaket(idPaket: bigint): Promise<Array<DistribusiRecord>>;
    getDistribusiBySasaran(idSasaran: bigint): Promise<Array<DistribusiRecord>>;
    getDistribusiByStatus(status: DistribusiStatus): Promise<Array<DistribusiRecord>>;
    getLaporanByKategori(kategori: Kategori, start: Time, end: Time): Promise<{
        distribusi: Array<DistribusiRecord>;
        paket: Array<PaketMBGRecord>;
        sasaran: Array<SasaranRecord>;
    }>;
    getPaket(_id: bigint): Promise<PaketMBGRecord | null>;
    getSasaran(_id: bigint): Promise<SasaranRecord | null>;
    getSemuaDistribusi(): Promise<Array<DistribusiRecord>>;
    getSemuaDistribusiSortedById(): Promise<Array<DistribusiRecord>>;
    getSemuaDistribusiSortedByTanggal(): Promise<Array<DistribusiRecord>>;
    getSemuaPaket(): Promise<Array<PaketMBGRecord>>;
    getSemuaPaketSortedById(): Promise<Array<PaketMBGRecord>>;
    getSemuaPaketSortedByNama(): Promise<Array<PaketMBGRecord>>;
    getSemuaSasaran(): Promise<Array<SasaranRecord>>;
    getSemuaSasaranSortedById(): Promise<Array<SasaranRecord>>;
    getSemuaSasaranSortedByNama(): Promise<Array<SasaranRecord>>;
    getStatistikDistribusi(): Promise<{
        totalDistribusi: bigint;
        totalSasaran: bigint;
        totalPaket: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    tambahPaket(jenis: Jenis, nama: string, keterangan: string | null): Promise<PaketMBGRecord>;
    tambahSasaran(nama: string, alamat: string, nomorIdentitas: string, catatan: string | null, kategori: Kategori | null): Promise<SasaranRecord>;
    ubahStatusSasaran(id: bigint, aktif: boolean): Promise<void>;
}
import type { BatchedDistribusiResult as _BatchedDistribusiResult, DistribusiRecord as _DistribusiRecord, DistribusiStatus as _DistribusiStatus, Jenis as _Jenis, Kategori as _Kategori, PaketMBGRecord as _PaketMBGRecord, PendingBatchedDistribusi as _PendingBatchedDistribusi, SasaranRecord as _SasaranRecord, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cariSasaranByNama(arg0: string): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.cariSasaranByNama(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cariSasaranByNama(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async catatDistribusiBatched(arg0: PendingBatchedDistribusi): Promise<BatchedDistribusiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.catatDistribusiBatched(to_candid_PendingBatchedDistribusi_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BatchedDistribusiResult_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.catatDistribusiBatched(to_candid_PendingBatchedDistribusi_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BatchedDistribusiResult_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterDistribusiByTanggal(arg0: Time, arg1: Time): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDistribusiByTanggal(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDistribusiByTanggal(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterSasaranByKategori(arg0: Kategori): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterSasaranByKategori(to_candid_Kategori_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterSasaranByKategori(to_candid_Kategori_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterSasaranByStatus(arg0: boolean): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterSasaranByStatus(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterSasaranByStatus(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataUntukLaporan(arg0: Time, arg1: Time): Promise<{
        distribusi: Array<DistribusiRecord>;
        paket: Array<PaketMBGRecord>;
        sasaran: Array<SasaranRecord>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataUntukLaporan(arg0, arg1);
                return from_candid_record_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataUntukLaporan(arg0, arg1);
            return from_candid_record_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistribusi(arg0: bigint): Promise<DistribusiRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistribusi(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistribusi(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistribusiByPaket(arg0: bigint): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistribusiByPaket(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistribusiByPaket(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistribusiBySasaran(arg0: bigint): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistribusiBySasaran(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistribusiBySasaran(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDistribusiByStatus(arg0: DistribusiStatus): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistribusiByStatus(to_candid_DistribusiStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistribusiByStatus(to_candid_DistribusiStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaporanByKategori(arg0: Kategori, arg1: Time, arg2: Time): Promise<{
        distribusi: Array<DistribusiRecord>;
        paket: Array<PaketMBGRecord>;
        sasaran: Array<SasaranRecord>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaporanByKategori(to_candid_Kategori_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_record_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaporanByKategori(to_candid_Kategori_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_record_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaket(arg0: bigint): Promise<PaketMBGRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaket(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaket(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSasaran(arg0: bigint): Promise<SasaranRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSasaran(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSasaran(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaDistribusi(): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaDistribusi();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaDistribusi();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaDistribusiSortedById(): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaDistribusiSortedById();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaDistribusiSortedById();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaDistribusiSortedByTanggal(): Promise<Array<DistribusiRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaDistribusiSortedByTanggal();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaDistribusiSortedByTanggal();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaPaket(): Promise<Array<PaketMBGRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaPaket();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaPaket();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaPaketSortedById(): Promise<Array<PaketMBGRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaPaketSortedById();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaPaketSortedById();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaPaketSortedByNama(): Promise<Array<PaketMBGRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaPaketSortedByNama();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaPaketSortedByNama();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaSasaran(): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaSasaran();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaSasaran();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaSasaranSortedById(): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaSasaranSortedById();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaSasaranSortedById();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSemuaSasaranSortedByNama(): Promise<Array<SasaranRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSemuaSasaranSortedByNama();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSemuaSasaranSortedByNama();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatistikDistribusi(): Promise<{
        totalDistribusi: bigint;
        totalSasaran: bigint;
        totalPaket: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistikDistribusi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistikDistribusi();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async tambahPaket(arg0: Jenis, arg1: string, arg2: string | null): Promise<PaketMBGRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahPaket(to_candid_Jenis_n47(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PaketMBGRecord_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahPaket(to_candid_Jenis_n47(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PaketMBGRecord_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async tambahSasaran(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: Kategori | null): Promise<SasaranRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahSasaran(arg0, arg1, arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
                return from_candid_SasaranRecord_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahSasaran(arg0, arg1, arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
            return from_candid_SasaranRecord_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async ubahStatusSasaran(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ubahStatusSasaran(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ubahStatusSasaran(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BatchedDistribusiResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchedDistribusiResult): BatchedDistribusiResult {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DistribusiRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistribusiRecord): DistribusiRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DistribusiStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DistribusiStatus): DistribusiStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Jenis_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Jenis): Jenis {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Kategori_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Kategori): Kategori {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaketMBGRecord_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaketMBGRecord): PaketMBGRecord {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SasaranRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SasaranRecord): SasaranRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DistribusiRecord]): DistribusiRecord | null {
    return value.length === 0 ? null : from_candid_DistribusiRecord_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaketMBGRecord]): PaketMBGRecord | null {
    return value.length === 0 ? null : from_candid_PaketMBGRecord_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SasaranRecord]): SasaranRecord | null {
    return value.length === 0 ? null : from_candid_SasaranRecord_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    alamat: string;
    nama: string;
    nomorIdentitas: string;
    kategori: _Kategori;
    catatan: [] | [string];
}): {
    id: bigint;
    status: Status;
    alamat: string;
    nama: string;
    nomorIdentitas: string;
    kategori: Kategori;
    catatan?: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        alamat: value.alamat,
        nama: value.nama,
        nomorIdentitas: value.nomorIdentitas,
        kategori: from_candid_Kategori_n15(_uploadFile, _downloadFile, value.kategori),
        catatan: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.catatan))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gagal: Array<{
        error: string;
        sasaranId: bigint;
    }>;
    sukses: Array<_DistribusiRecord>;
}): {
    gagal: Array<{
        error: string;
        sasaranId: bigint;
    }>;
    sukses: Array<DistribusiRecord>;
} {
    return {
        gagal: value.gagal,
        sukses: from_candid_vec_n24(_uploadFile, _downloadFile, value.sukses)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    idPaket: bigint;
    idSasaran: bigint;
    keterangan: [] | [string];
    statusDistribusi: _DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: _Time;
}): {
    id: bigint;
    idPaket: bigint;
    idSasaran: bigint;
    keterangan?: string;
    statusDistribusi: DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: Time;
} {
    return {
        id: value.id,
        idPaket: value.idPaket,
        idSasaran: value.idSasaran,
        keterangan: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.keterangan)),
        statusDistribusi: from_candid_DistribusiStatus_n27(_uploadFile, _downloadFile, value.statusDistribusi),
        jumlahPaket: value.jumlahPaket,
        tanggalDistribusi: value.tanggalDistribusi
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email: [] | [string];
}): {
    name: string;
    role: string;
    email?: string;
} {
    return {
        name: value.name,
        role: value.role,
        email: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distribusi: Array<_DistribusiRecord>;
    paket: Array<_PaketMBGRecord>;
    sasaran: Array<_SasaranRecord>;
}): {
    distribusi: Array<DistribusiRecord>;
    paket: Array<PaketMBGRecord>;
    sasaran: Array<SasaranRecord>;
} {
    return {
        distribusi: from_candid_vec_n24(_uploadFile, _downloadFile, value.distribusi),
        paket: from_candid_vec_n37(_uploadFile, _downloadFile, value.paket),
        sasaran: from_candid_vec_n10(_uploadFile, _downloadFile, value.sasaran)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nama: string;
    jenis: _Jenis;
    keterangan: [] | [string];
}): {
    id: bigint;
    nama: string;
    jenis: Jenis;
    keterangan?: string;
} {
    return {
        id: value.id,
        nama: value.nama,
        jenis: from_candid_Jenis_n40(_uploadFile, _downloadFile, value.jenis),
        keterangan: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.keterangan))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aktif: null;
} | {
    nonAktif: null;
}): Status {
    return "aktif" in value ? Status.aktif : "nonAktif" in value ? Status.nonAktif : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balita: null;
} | {
    tidakDitentukan: null;
} | {
    ibuMenyusui: null;
} | {
    ibuHamil: null;
}): Kategori {
    return "balita" in value ? Kategori.balita : "tidakDitentukan" in value ? Kategori.tidakDitentukan : "ibuMenyusui" in value ? Kategori.ibuMenyusui : "ibuHamil" in value ? Kategori.ibuHamil : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    terdistribusi: null;
} | {
    dalamProses: null;
} | {
    tidakTerkirim: null;
}): DistribusiStatus {
    return "pending" in value ? DistribusiStatus.pending : "terdistribusi" in value ? DistribusiStatus.terdistribusi : "dalamProses" in value ? DistribusiStatus.dalamProses : "tidakTerkirim" in value ? DistribusiStatus.tidakTerkirim : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    susuTambahan: null;
} | {
    lainnya: string;
} | {
    makananSiapSaji: null;
} | {
    multivitamin: null;
} | {
    paketSembako: null;
}): {
    __kind__: "susuTambahan";
    susuTambahan: null;
} | {
    __kind__: "lainnya";
    lainnya: string;
} | {
    __kind__: "makananSiapSaji";
    makananSiapSaji: null;
} | {
    __kind__: "multivitamin";
    multivitamin: null;
} | {
    __kind__: "paketSembako";
    paketSembako: null;
} {
    return "susuTambahan" in value ? {
        __kind__: "susuTambahan",
        susuTambahan: value.susuTambahan
    } : "lainnya" in value ? {
        __kind__: "lainnya",
        lainnya: value.lainnya
    } : "makananSiapSaji" in value ? {
        __kind__: "makananSiapSaji",
        makananSiapSaji: value.makananSiapSaji
    } : "multivitamin" in value ? {
        __kind__: "multivitamin",
        multivitamin: value.multivitamin
    } : "paketSembako" in value ? {
        __kind__: "paketSembako",
        paketSembako: value.paketSembako
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SasaranRecord>): Array<SasaranRecord> {
    return value.map((x)=>from_candid_SasaranRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DistribusiRecord>): Array<DistribusiRecord> {
    return value.map((x)=>from_candid_DistribusiRecord_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaketMBGRecord>): Array<PaketMBGRecord> {
    return value.map((x)=>from_candid_PaketMBGRecord_n38(_uploadFile, _downloadFile, x));
}
function to_candid_DistribusiStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DistribusiStatus): _DistribusiStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Jenis_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Jenis): _Jenis {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Kategori_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Kategori): _Kategori {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_PendingBatchedDistribusi_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PendingBatchedDistribusi): _PendingBatchedDistribusi {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Kategori | null): [] | [_Kategori] {
    return value === null ? candid_none() : candid_some(to_candid_Kategori_n29(_uploadFile, _downloadFile, value));
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idPaket: bigint;
    sasaranIds: Array<bigint>;
    keterangan?: string;
    statusDistribusi: DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: Time;
}): {
    idPaket: bigint;
    sasaranIds: Array<bigint>;
    keterangan: [] | [string];
    statusDistribusi: _DistribusiStatus;
    jumlahPaket: bigint;
    tanggalDistribusi: _Time;
} {
    return {
        idPaket: value.idPaket,
        sasaranIds: value.sasaranIds,
        keterangan: value.keterangan ? candid_some(value.keterangan) : candid_none(),
        statusDistribusi: to_candid_DistribusiStatus_n20(_uploadFile, _downloadFile, value.statusDistribusi),
        jumlahPaket: value.jumlahPaket,
        tanggalDistribusi: value.tanggalDistribusi
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email?: string;
}): {
    name: string;
    role: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        role: value.role,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DistribusiStatus): {
    pending: null;
} | {
    terdistribusi: null;
} | {
    dalamProses: null;
} | {
    tidakTerkirim: null;
} {
    return value == DistribusiStatus.pending ? {
        pending: null
    } : value == DistribusiStatus.terdistribusi ? {
        terdistribusi: null
    } : value == DistribusiStatus.dalamProses ? {
        dalamProses: null
    } : value == DistribusiStatus.tidakTerkirim ? {
        tidakTerkirim: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Kategori): {
    balita: null;
} | {
    tidakDitentukan: null;
} | {
    ibuMenyusui: null;
} | {
    ibuHamil: null;
} {
    return value == Kategori.balita ? {
        balita: null
    } : value == Kategori.tidakDitentukan ? {
        tidakDitentukan: null
    } : value == Kategori.ibuMenyusui ? {
        ibuMenyusui: null
    } : value == Kategori.ibuHamil ? {
        ibuHamil: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "susuTambahan";
    susuTambahan: null;
} | {
    __kind__: "lainnya";
    lainnya: string;
} | {
    __kind__: "makananSiapSaji";
    makananSiapSaji: null;
} | {
    __kind__: "multivitamin";
    multivitamin: null;
} | {
    __kind__: "paketSembako";
    paketSembako: null;
}): {
    susuTambahan: null;
} | {
    lainnya: string;
} | {
    makananSiapSaji: null;
} | {
    multivitamin: null;
} | {
    paketSembako: null;
} {
    return value.__kind__ === "susuTambahan" ? {
        susuTambahan: value.susuTambahan
    } : value.__kind__ === "lainnya" ? {
        lainnya: value.lainnya
    } : value.__kind__ === "makananSiapSaji" ? {
        makananSiapSaji: value.makananSiapSaji
    } : value.__kind__ === "multivitamin" ? {
        multivitamin: value.multivitamin
    } : value.__kind__ === "paketSembako" ? {
        paketSembako: value.paketSembako
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
